### ISSUE TITLE
Release 1.1.0 setup local api pick up TEST data

### ISSUE THREAD

**Issue by MZorzy** [StephanU/MyGekko#113]
hi StephanU
i'm on MyGekko 1.1.0 (removed and installed as new) set up with local ip (192.168...) and the same user/password i use on liveviewer.my-gekko.com it show "success" BUT it pick up and show all TEST data, not data from my Slide2 v6800-17

same if setup with wrong user/password*.  "success" but populate with TEST data 

if i setup with plus API, same username, i have/get/set all my real data  . * i try local https://192.168.8.XXX/api/v1/var/blinds/status?username=USER&password=PASSWORD and work so not wrong user/pass

**Comment by StephanU** [comment]
Hi @MZorzy
yes, there was a bug regarding the local connection. I fixed it in the newest release (1.2.0). Could you please try it?

Are all the other features (still) working in your environment?

**Comment by StephanU** [comment]
There was another bug when connecting locally, please try 1.2.1 :)

**Comment by MZorzy** [comment]
hi  now give me "Nome utente/Password/Indirizzo IP errati. Per i dettagli, consultare i registri."
  Logger: custom_components.mygekko.config_flow
Source: custom_components/mygekko/config_flow.py:185
Integration: MyGekko ([documentation](https://github.com/stephanu/mygekko), [issues](https://github.com/stephanu/mygekko/issues))
First occurred: 21:37:46 (4 occurrences)
Last logged: 21:40:20
ClientConnectorError

**Comment by StephanU** [comment]
Please check the HomeAssistant logs for error form the MyGekko integration. Something should be in there...

**Comment by MZorzy** [comment]
on logs there is not "mygekko" menu , but have this on "home assistant core" :
Logger: custom_components.mygekko.config_flow
Source: custom_components/mygekko/config_flow.py:185
Integration: mygekko ([documentation](https://github.com/stephanu/mygekko), [issues](https://github.com/stephanu/mygekko/issues))
First occurred: 22:06:38 (1 occurrences)
Last logged: 22:06:38
ClientConnectorError

**Comment by MZorzy** [comment]
1.2.3  after ip user pass give "success"  but it go in loop trying to initialize. not add device etc
log




2023-12-11 20:55:10.645 ERROR (MainThread) [custom_components.mygekko] Error fetching mygekko data: 
2023-12-11 20:55:10.646 ERROR (MainThread) [custom_components.mygekko] async_refresh failed
NoneType: None
2023-12-11 20:56:33.717 ERROR (MainThread) [custom_components.mygekko] _async_update_data failed
Traceback (most recent call last):
  File "/config/custom_components/mygekko/__init__.py", line 145, in _async_update_data
    return await self.api.read_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/__init__.py", line 81, in read_data
    await self._data_provider.read_data()
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/data_provider.py", line 155, in read_data
    self.status = json.loads(response_text)
    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/data_provider.py", line 70, in status
    subscriber.update_status(self._status)
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/EnergyCosts.py", line 92, in update_status
    self._data[key]["values"] = self._decode_values(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/EnergyCosts.py", line 76, in _decode_values
    values.append(self._transform_value(value_descriptions[index], value_parts))
                                        ~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
2023-12-11 20:56:33.730 ERROR (MainThread) [custom_components.mygekko] Error fetching mygekko data: 
2023-12-11 20:56:33.730 ERROR (MainThread) [custom_components.mygekko] async_refresh failed
NoneType: None
2023-12-11 20:57:19.285 ERROR (MainThread) [custom_components.mygekko] _async_update_data failed
Traceback (most recent call last):
  File "/config/custom_components/mygekko/__init__.py", line 145, in _async_update_data
    return await self.api.read_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/__init__.py", line 81, in read_data
    await self._data_provider.read_data()
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/data_provider.py", line 155, in read_data
    self.status = json.loads(response_text)
    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/data_provider.py", line 70, in status
    subscriber.update_status(self._status)
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/EnergyCosts.py", line 92, in update_status
    self._data[key]["values"] = self._decode_values(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/EnergyCosts.py", line 76, in _decode_values
    values.append(self._transform_value(value_descriptions[index], value_parts))
                                        ~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
2023-12-11 20:57:19.297 ERROR (MainThread) [custom_components.mygekko] Error fetching mygekko data: 
2023-12-11 20:57:19.298 ERROR (MainThread) [custom_components.mygekko] async_refresh failed
NoneType: None
2023-12-11 20:57:27.170 ERROR (MainThread) [custom_components.mygekko] _async_update_data failed
Traceback (most recent call last):
  File "/config/custom_components/mygekko/__init__.py", line 145, in _async_update_data
    return await self.api.read_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/__init__.py", line 81, in read_data
    await self._data_provider.read_data()
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/data_provider.py", line 155, in read_data
    self.status = json.loads(response_text)
    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/data_provider.py", line 70, in status
    subscriber.update_status(self._status)
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/EnergyCosts.py", line 92, in update_status
    self._data[key]["values"] = self._decode_values(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/EnergyCosts.py", line 76, in _decode_values
    values.append(self._transform_value(value_descriptions[index], value_parts))
                                        ~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
2023-12-11 20:57:27.181 ERROR (MainThread) [custom_components.mygekko] Error fetching mygekko data: 
2023-12-11 20:57:27.182 ERROR (MainThread) [custom_components.mygekko] async_refresh failed
NoneType: None

**Comment by StephanU** [comment]
Thanks again for the logs. I think I found the problem... Please try 1.2.4

**Comment by MZorzy** [comment]
oh yeah. 1.2.4 work on local now. thank you !!

got 108 device and 219 entity. light work, dimmer work. cover work.... good
